name: CI/CD Angular DevOps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build Angular app
        run: npm run build

      - name: Build Docker image with tag
        run: docker build -t angular-test:${{ github.run_number }} .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag angular-test:${{ github.run_number }} ${{ secrets.DOCKER_USERNAME }}/angular-test:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/angular-test:${{ github.run_number }}
